name: Job Service CI

on:
  push:
    branches: [main, feat/cdci]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Package install
        run: yarn install --frozen-lockfile

      - name: Docker build
        run: docker build -t jobs-api:1.0 .
