name: Job Service CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/node@v2
        with:
          node-version: 14.x

      - name: Package install
        run: yarn install --frozen-lockfile